### PR TITLE
qTip API (@idoa01)

### PR DESCRIPTION
**Pull request by chenasraf**

### CODE REVIEW

**Comment by chenasraf** [comment]
@idoa01 do you wanna take a look at this before I merge?

**Comment by idoa01** [comment]
Looks good 👍 Thanks!
Only thing that I thought of just now, is maybe add a `if qtipApi != undefined` before adding the promise defer and resolve (lines 59 and 106), so to conserve resources if the user doesn't want an api object.

**Comment by chenasraf** [comment]
Ok I'll take care of that later today and merge

**Comment by idoa01** [comment]
cool, thanks 😃

**Comment by idoa01** [comment]
hey, can you possibly merge this today? thanks! 👍

**Comment by chenasraf** [comment]
Sorry, completely forgot about this 😅  holidays and stuff. Merging

**Pull request merged**
